//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSHG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrators
    {
        public string Alogin { get; set; }
        public string Apassword { get; set; }
        public string AName { get; set; }
        public string ALastName { get; set; }
        public string ASecondName { get; set; }
        public System.DateTime DateofBirth { get; set; }
    }
}
