//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSHG
{
    using System;
    using System.Collections.Generic;
    
    public partial class BALLS
    {
        public int IDUser { get; set; }
        public int IDFilm { get; set; }
        public int Mark { get; set; }
        public string Comment { get; set; }
    
        public virtual Films Films { get; set; }
        public virtual Users Users { get; set; }
    }
}
