//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSHG
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREATORSOFFILMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CREATORSOFFILMS()
        {
            this.roleofactor = new HashSet<roleofactor>();
        }
    
        public int IDCreator { get; set; }
        public string AcName { get; set; }
        public string AcLastName { get; set; }
        public string AcSecondName { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public System.DateTime Dateofcareer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<roleofactor> roleofactor { get; set; }
    }
}
