//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSHG
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataUsers
    {
        public string LoginUs { get; set; }
        public string PasswordUs { get; set; }
        public int IDUser { get; set; }

        //изменено тут
        private string PROV1, PROV2, PROV3, PROV4, PROV5, PROV6;
        public virtual Users Users { get; set; }
    }
}
