//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSHG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Films
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Films()
        {
            this.BALLS = new HashSet<BALLS>();
            this.roleofactor = new HashSet<roleofactor>();
        }
    
        public int IDFilm { get; set; }
        public string NameofFilm { get; set; }
        public int IDCountry { get; set; }
        public int AgeRestriction { get; set; }
        public int rating { get; set; }
        public int IDgenre { get; set; }
        public System.DateTime DateofCreate { get; set; }
        public string Poster { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BALLS> BALLS { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual GENRES GENRES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<roleofactor> roleofactor { get; set; }
    }
}
