//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSHG
{
    using System;
    using System.Collections.Generic;
    
    public partial class roleofactor
    {
        public int IDCreator { get; set; }
        public int IDFilm { get; set; }
        public string RoleofActor1 { get; set; }
    
        public virtual CREATORSOFFILMS CREATORSOFFILMS { get; set; }
        public virtual Films Films { get; set; }
    }
}
